//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrushBot.Application.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrushBot.Application.Localization.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send my location 📍.
        /// </summary>
        internal static string Button_AskCity_SendLocation {
            get {
                return ResourceManager.GetString("Button.AskCity.SendLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos 📸.
        /// </summary>
        internal static string Button_AskMedia_Photo {
            get {
                return ResourceManager.GetString("Button.AskMedia.Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video 🎬.
        /// </summary>
        internal static string Button_AskMedia_Video {
            get {
                return ResourceManager.GetString("Button.AskMedia.Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman 💅.
        /// </summary>
        internal static string Button_AskSex_Female {
            get {
                return ResourceManager.GetString("Button.AskSex.Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man 💪.
        /// </summary>
        internal static string Button_AskSex_Male {
            get {
                return ResourceManager.GetString("Button.AskSex.Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        internal static string Button_AskSexFilter_Any {
            get {
                return ResourceManager.GetString("Button.AskSexFilter.Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women 💅.
        /// </summary>
        internal static string Button_AskSexFilter_Female {
            get {
                return ResourceManager.GetString("Button.AskSexFilter.Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men 💪.
        /// </summary>
        internal static string Button_AskSexFilter_Male {
            get {
                return ResourceManager.GetString("Button.AskSexFilter.Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Change age.
        /// </summary>
        internal static string Button_EditFilters_ChangeAge {
            get {
                return ResourceManager.GetString("Button.EditFilters.ChangeAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💪💅 Change gender.
        /// </summary>
        internal static string Button_EditFilters_ChangeSex {
            get {
                return ResourceManager.GetString("Button.EditFilters.ChangeSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👤 Start from scratch.
        /// </summary>
        internal static string Button_EditProfile_ChangeAll {
            get {
                return ResourceManager.GetString("Button.EditProfile.ChangeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌍 Change city.
        /// </summary>
        internal static string Button_EditProfile_ChangeCity {
            get {
                return ResourceManager.GetString("Button.EditProfile.ChangeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️ Change description.
        /// </summary>
        internal static string Button_EditProfile_ChangeDescription {
            get {
                return ResourceManager.GetString("Button.EditProfile.ChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📷🎬 Change media.
        /// </summary>
        internal static string Button_EditProfile_ChangeMedia {
            get {
                return ResourceManager.GetString("Button.EditProfile.ChangeMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👤 Edit profile.
        /// </summary>
        internal static string Button_Profile_Edit {
            get {
                return ResourceManager.GetString("Button.Profile.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Change filters.
        /// </summary>
        internal static string Button_Profile_Filters {
            get {
                return ResourceManager.GetString("Button.Profile.Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Settings.
        /// </summary>
        internal static string Button_Profile_Settings {
            get {
                return ResourceManager.GetString("Button.Profile.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 View matches.
        /// </summary>
        internal static string Button_Profile_ViewMatches {
            get {
                return ResourceManager.GetString("Button.Profile.ViewMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Start search.
        /// </summary>
        internal static string Button_Profile_ViewProfiles {
            get {
                return ResourceManager.GetString("Button.Profile.ViewProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Delete profile.
        /// </summary>
        internal static string Button_Settings_DeleteProfile {
            get {
                return ResourceManager.GetString("Button.Settings.DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide emoji.
        /// </summary>
        internal static string Button_Settings_HideEmoji {
            get {
                return ResourceManager.GetString("Button.Settings.HideEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Language.
        /// </summary>
        internal static string Button_Settings_Language {
            get {
                return ResourceManager.GetString("Button.Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show emoji.
        /// </summary>
        internal static string Button_Settings_ShowEmoji {
            get {
                return ResourceManager.GetString("Button.Settings.ShowEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly – {0}€.
        /// </summary>
        internal static string Button_Settings_SubscribeMonthly {
            get {
                return ResourceManager.GetString("Button.Settings.SubscribeMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly – {0}€ (-{1}%).
        /// </summary>
        internal static string Button_Settings_SubscribeYearly {
            get {
                return ResourceManager.GetString("Button.Settings.SubscribeYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Crush Premium.
        /// </summary>
        internal static string Button_Settings_Subscription {
            get {
                return ResourceManager.GetString("Button.Settings.Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◀️ Back.
        /// </summary>
        internal static string Button_Shared_Back {
            get {
                return ResourceManager.GetString("Button.Shared.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue ▶️.
        /// </summary>
        internal static string Button_Shared_Continue {
            get {
                return ResourceManager.GetString("Button.Shared.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep as is ▶️.
        /// </summary>
        internal static string Button_Shared_Current {
            get {
                return ResourceManager.GetString("Button.Shared.Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How old are you?.
        /// </summary>
        internal static string Message_AskAge_AskAge {
            get {
                return ResourceManager.GetString("Message.AskAge.AskAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number or age with a hyphen\. Allowed range: __{0}\-{1}__\..
        /// </summary>
        internal static string Message_AskAgeFilter_AskAgeFilter {
            get {
                return ResourceManager.GetString("Message.AskAgeFilter.AskAgeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number or age with a hyphen\. Allowed range: __{0}\-{1}__\.
        ///
        ///||_✨ Subscription range: {2}\-{3}_||.
        /// </summary>
        internal static string Message_AskAgeFilter_AskAgeFilterSub {
            get {
                return ResourceManager.GetString("Message.AskAgeFilter.AskAgeFilterSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which city?
        ///
        ///_Type it in, choose geolocation on the map 📎 or send your current 📍_.
        /// </summary>
        internal static string Message_AskCity_AskCity {
            get {
                return ResourceManager.GetString("Message.AskCity.AskCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⌛ The external service didn&apos;t respond, please try again..
        /// </summary>
        internal static string Message_AskCity_ExternalError {
            get {
                return ResourceManager.GetString("Message.AskCity.ExternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌🔍 City not found, please try again..
        /// </summary>
        internal static string Message_AskCity_InvalidCity {
            get {
                return ResourceManager.GetString("Message.AskCity.InvalidCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a profile description\. Continue to leave the field blank\.
        ///
        ///_The text can be formatted\._.
        /// </summary>
        internal static string Message_AskDescription_AskDescription {
            get {
                return ResourceManager.GetString("Message.AskDescription.AskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which language do you prefer?.
        /// </summary>
        internal static string Message_AskLanguage_AskLanguage {
            get {
                return ResourceManager.GetString("Message.AskLanguage.AskLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what to upload: photos or a short video..
        /// </summary>
        internal static string Message_AskMedia_AskMedia {
            get {
                return ResourceManager.GetString("Message.AskMedia.AskMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your name?.
        /// </summary>
        internal static string Message_AskName_AskName {
            get {
                return ResourceManager.GetString("Message.AskName.AskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your gender?.
        /// </summary>
        internal static string Message_AskSex_AskSex {
            get {
                return ResourceManager.GetString("Message.AskSex.AskSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you looking for?.
        /// </summary>
        internal static string Message_AskSexFilter_AskSexFilter {
            get {
                return ResourceManager.GetString("Message.AskSexFilter.AskSexFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Found {0}. Please select yours..
        /// </summary>
        internal static string Message_ChooseCity_ChooseCity {
            get {
                return ResourceManager.GetString("Message.ChooseCity.ChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more or proceed to the next step\..
        /// </summary>
        internal static string Message_ChoosePhoto_AskAddPhoto {
            get {
                return ResourceManager.GetString("Message.ChoosePhoto.AskAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload up to {0} photos one by one\.
        ///
        ///_Attach an image from the gallery, not a file\._.
        /// </summary>
        internal static string Message_ChoosePhoto_ChoosePhoto {
            get {
                return ResourceManager.GetString("Message.ChoosePhoto.ChoosePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} photos added..
        /// </summary>
        internal static string Message_ChoosePhoto_PhotoAdded {
            get {
                return ResourceManager.GetString("Message.ChoosePhoto.PhotoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a video from {0} to {1} seconds long\.
        ///
        ///_Attach a video from the gallery, not a file\._.
        /// </summary>
        internal static string Message_ChooseVideo_ChooseVideo {
            get {
                return ResourceManager.GetString("Message.ChooseVideo.ChooseVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Video duration must be between {0} and {1} seconds..
        /// </summary>
        internal static string Message_ChooseVideo_InvalidDuration {
            get {
                return ResourceManager.GetString("Message.ChooseVideo.InvalidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚨 Please enter your profile name to confirm deletion\. This action cannot be undone\.
        ///__*{0}*__.
        /// </summary>
        internal static string Message_DeleteProfile_DeleteProfile {
            get {
                return ResourceManager.GetString("Message.DeleteProfile.DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in your profile..
        /// </summary>
        internal static string Message_Profile_Profile {
            get {
                return ResourceManager.GetString("Message.Profile.Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to start the bot 🤖.
        /// </summary>
        internal static string Message_Registration_PressToStart {
            get {
                return ResourceManager.GetString("Message.Registration.PressToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ The age can be between {0} and {1}..
        /// </summary>
        internal static string Message_Shared_AgeValidation {
            get {
                return ResourceManager.GetString("Message.Shared.AgeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 Boost increased\! *\({0}\/{1}\)*
        ///
        ///_Visit for {1} days in a row for maximum effect\._.
        /// </summary>
        internal static string Message_Shared_BoostIncreased {
            get {
                return ResourceManager.GetString("Message.Shared.BoostIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 Maximum boost\! *\({0}\/{0}\)*
        ///
        ///_Keep visiting to maintain the effect\._.
        /// </summary>
        internal static string Message_Shared_BoostKeep {
            get {
                return ResourceManager.GetString("Message.Shared.BoostKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an action..
        /// </summary>
        internal static string Message_Shared_ChooseAction {
            get {
                return ResourceManager.GetString("Message.Shared.ChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌍 Your city is set to __{0}__\..
        /// </summary>
        internal static string Message_Shared_CityEntered {
            get {
                return ResourceManager.GetString("Message.Shared.CityEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ The length must be between {0} and {1} characters..
        /// </summary>
        internal static string Message_Shared_InvalidLength {
            get {
                return ResourceManager.GetString("Message.Shared.InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ The minimum resolution is {0}x{0} pixels..
        /// </summary>
        internal static string Message_Shared_InvalidResolution {
            get {
                return ResourceManager.GetString("Message.Shared.InvalidResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🕒 No activity for a long time\..
        /// </summary>
        internal static string Message_Shared_LowWeight {
            get {
                return ResourceManager.GetString("Message.Shared.LowWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profile will be excluded from search\._.
        /// </summary>
        internal static string Message_Shared_LowWeightNoSub {
            get {
                return ResourceManager.GetString("Message.Shared.LowWeightNoSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _✨ Thanks to *Crush Premium*, your profile will not be excluded from search\._.
        /// </summary>
        internal static string Message_Shared_LowWeightSub {
            get {
                return ResourceManager.GetString("Message.Shared.LowWeightSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Don\&apos;t forget to visit: the more often you visit, the higher your profile\&apos;s relevance\._.
        /// </summary>
        internal static string Message_Shared_Relevance {
            get {
                return ResourceManager.GetString("Message.Shared.Relevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛠️ Oops! Something went wrong. Please try again later..
        /// </summary>
        internal static string Message_Shared_UnhandledError {
            get {
                return ResourceManager.GetString("Message.Shared.UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Thank you for subscribing *Crush Premium*\. Here&apos;s what is now unlocked:.
        /// </summary>
        internal static string Message_Subscription_Active {
            get {
                return ResourceManager.GetString("Message.Subscription.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 💚 Unlimited likes
        ///• 📅 Extended age filter
        ///• 🚀 Maximum profile boost
        ///• 🕒 Profile stays in search
        ///• ✨ Exclusive emoji by your name
        ///• 📷 2 more profile photos
        ///• 🎬 x2 profile video length
        ///• ✏️ x2 profile description length.
        /// </summary>
        internal static string Message_Subscription_Features {
            get {
                return ResourceManager.GetString("Message.Subscription.Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Go beyond the limits and unlock exclusive features by subscribing *Crush Premium*:.
        /// </summary>
        internal static string Message_Subscription_Inactive {
            get {
                return ResourceManager.GetString("Message.Subscription.Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _*[Subscription management]({0})*_.
        /// </summary>
        internal static string Message_Subscription_Management {
            get {
                return ResourceManager.GetString("Message.Subscription.Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 Enjoy a *{0}%* discount on your first year&apos;s purchase\..
        /// </summary>
        internal static string Message_Subscription_Subscribe {
            get {
                return ResourceManager.GetString("Message.Subscription.Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅🔄 Age filter temporarily reset..
        /// </summary>
        internal static string Message_ViewProfile_AgeFilterReset {
            get {
                return ResourceManager.GetString("Message.ViewProfile.AgeFilterReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💚 New like\! *\({0}\)*.
        /// </summary>
        internal static string Message_ViewProfile_NewLike {
            get {
                return ResourceManager.GetString("Message.ViewProfile.NewLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 New match\! *\({0}\)*.
        /// </summary>
        internal static string Message_ViewProfile_NewMatch {
            get {
                return ResourceManager.GetString("Message.ViewProfile.NewMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new profiles available. Share the bot with your friends!.
        /// </summary>
        internal static string Message_ViewProfile_NoProfiles {
            get {
                return ResourceManager.GetString("Message.ViewProfile.NoProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Press any button to view\._.
        /// </summary>
        internal static string Message_ViewProfile_PressAny {
            get {
                return ResourceManager.GetString("Message.ViewProfile.PressAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Finish with the current profile\._.
        /// </summary>
        internal static string Message_ViewProfile_Proceed {
            get {
                return ResourceManager.GetString("Message.ViewProfile.Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start search to view 🔍_.
        /// </summary>
        internal static string Message_ViewProfile_StartSearch {
            get {
                return ResourceManager.GetString("Message.ViewProfile.StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Liked you\!_ 💚.
        /// </summary>
        internal static string Message_ViewProfile_StatusLiked {
            get {
                return ResourceManager.GetString("Message.ViewProfile.StatusLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _This is a match\!_ 🎉 {0}.
        /// </summary>
        internal static string Message_ViewProfile_StatusMatched {
            get {
                return ResourceManager.GetString("Message.ViewProfile.StatusMatched", resourceCulture);
            }
        }
    }
}
