//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrushBot.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrushBot.Localization.Resources.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The age can be between {0} and {1}..
        /// </summary>
        internal static string Message_AskAgeState_AgeValidation {
            get {
                return ResourceManager.GetString("Message.AskAgeState.AgeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How old are you?.
        /// </summary>
        internal static string Message_AskAgeState_AskAge {
            get {
                return ResourceManager.GetString("Message.AskAgeState.AskAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What’s your city? Type it in or send any location..
        /// </summary>
        internal static string Message_AskCityState_AskCity {
            get {
                return ResourceManager.GetString("Message.AskCityState.AskCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City not found, please try again..
        /// </summary>
        internal static string Message_AskCityState_InvalidCity {
            get {
                return ResourceManager.GetString("Message.AskCityState.InvalidCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send my location.
        /// </summary>
        internal static string Message_AskCityState_SendLocation {
            get {
                return ResourceManager.GetString("Message.AskCityState.SendLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which language do you prefer?.
        /// </summary>
        internal static string Message_AskLanguageState_AskLanguage {
            get {
                return ResourceManager.GetString("Message.AskLanguageState.AskLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s your name?.
        /// </summary>
        internal static string Message_AskNameState_AskName {
            get {
                return ResourceManager.GetString("Message.AskNameState.AskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can be between {0} and {1} characters long..
        /// </summary>
        internal static string Message_AskNameState_NameValidation {
            get {
                return ResourceManager.GetString("Message.AskNameState.NameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s your gender?.
        /// </summary>
        internal static string Message_AskSexState_AskSex {
            get {
                return ResourceManager.GetString("Message.AskSexState.AskSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        internal static string Message_AskSexState_SendFemale {
            get {
                return ResourceManager.GetString("Message.AskSexState.SendFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        internal static string Message_AskSexState_SendMale {
            get {
                return ResourceManager.GetString("Message.AskSexState.SendMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong. We&apos;re working on it. Please try again later..
        /// </summary>
        internal static string Message_Error_ServiceError {
            get {
                return ResourceManager.GetString("Message.Error.ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to start the bot..
        /// </summary>
        internal static string Message_RegistrationState_PressToStart {
            get {
                return ResourceManager.GetString("Message.RegistrationState.PressToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one of the predefined options on the keyboard..
        /// </summary>
        internal static string Message_Validation_ChooseOption {
            get {
                return ResourceManager.GetString("Message.Validation.ChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message type..
        /// </summary>
        internal static string Message_Validation_InvalidMessageType {
            get {
                return ResourceManager.GetString("Message.Validation.InvalidMessageType", resourceCulture);
            }
        }
    }
}
